---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:6
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
  - port: 27017
    targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: 791358130074.dkr.ecr.ap-south-1.amazonaws.com/streaming-auth:latest
        ports:
        - containerPort: 3001
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017/streamingapp"
        - name: JWT_SECRET
          value: "changeme"
        - name: CLIENT_URLS
          value: "http://localhost:3000,http://localhost:8080,http://a155dd69517c74fe786edc32dc8c85fd-96795277.ap-south-1.elb.amazonaws.com"
---
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
  - port: 3001
    targetPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streaming
  template:
    metadata:
      labels:
        app: streaming
    spec:
      containers:
      - name: streaming
        image: 791358130074.dkr.ecr.ap-south-1.amazonaws.com/streaming-streaming:latest
        ports:
        - containerPort: 3002
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017/streamingapp"
        - name: JWT_SECRET
          value: "changeme"
        - name: CLIENT_URLS
          value: "http://localhost:3000,http://localhost:8080,http://a155dd69517c74fe786edc32dc8c85fd-96795277.ap-south-1.elb.amazonaws.com"
---
apiVersion: v1
kind: Service
metadata:
  name: streaming
spec:
  type: ClusterIP
  selector:
    app: streaming
  ports:
  - port: 3002
    targetPort: 3002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
      - name: admin
        image: 791358130074.dkr.ecr.ap-south-1.amazonaws.com/streaming-admin:latest
        ports:
        - containerPort: 3003
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017/streamingapp"
        - name: JWT_SECRET
          value: "changeme"
        - name: CLIENT_URLS
          value: "http://localhost:3000,http://localhost:8080,http://a155dd69517c74fe786edc32dc8c85fd-96795277.ap-south-1.elb.amazonaws.com"
---
apiVersion: v1
kind: Service
metadata:
  name: admin
spec:
  type: ClusterIP
  selector:
    app: admin
  ports:
  - port: 3003
    targetPort: 3003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
      - name: chat
        image: 791358130074.dkr.ecr.ap-south-1.amazonaws.com/streaming-chat:latest
        ports:
        - containerPort: 3004
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017/streamingapp"
        - name: JWT_SECRET
          value: "changeme"
        - name: CLIENT_URLS
          value: "http://localhost:3000,http://localhost:8080,http://a155dd69517c74fe786edc32dc8c85fd-96795277.ap-south-1.elb.amazonaws.com"
---
apiVersion: v1
kind: Service
metadata:
  name: chat
spec:
  type: ClusterIP
  selector:
    app: chat
  ports:
  - port: 3004
    targetPort: 3004
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 791358130074.dkr.ecr.ap-south-1.amazonaws.com/streaming-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
